- name: Download oh-my-zsh installation script
  get_url:
    url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/oh-my-zsh-installer.sh
    mode: "0755"

- name: Run oh-my-zsh installation script
  shell: bash /tmp/oh-my-zsh-installer.sh

# - name: Change permissions of oh-my-zsh installation script
#   file:
#     path: ~/.oh-my-zsh/oh-my-zsh.sh
#     mode: "0755"

# - name: Find shell scripts in directory
#   ansible.builtin.find:
#     paths: ~/.oh-my-zsh
#     patterns: "*.*sh"
#     recurse: true
#   register: shell_scripts

# - name: Change permissions of shell scripts
#   ansible.builtin.file:
#     path: "{{ item.path }}"
#     mode: "0755"
#   loop: "{{ shell_scripts.files }}"

- name: Create plugins directory
  file:
    path: ~/.oh-my-zsh/plugins
    state: directory

- name: Create plugins directory
  file:
    path: ~/.oh-my-zsh/custom/plugins
    state: directory

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"

- name: Download oh-my-zsh installation script
  get_url:
    url: https://raw.githubusercontent.com/rupa/z/master/z.sh
    dest: ~/.oh-my-zsh/custom/plugins/z.sh
    mode: "0755"

- name: Change shell to zsh
  shell: chsh -s $(which zsh)

- name: Backup dotfiles
  shell: |
    [ -f ~/.bashrc ] && mv ~/.bashrc ~/.bashrc_old
    [ -f ~/.zshrc ] && mv ~/.zshrc ~/.zshrc_old
    [ -f ~/.profile ] && mv ~/.profile ~/.profile_old
  ignore_errors: true

- name: Clone shell repo
  ansible.builtin.git:
    repo: "https://github.com/ugudlado/shell.git"
    dest: ~/shell
    version: feature/ansible-conversion

- name: Stow dotfiles
  shell: |
    cd ~/shell
    stow -t ~ dotfiles
