- name: Install Ansible collection
  shell: ansible-galaxy collection install community.general
  delegate_to: localhost
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  when: ansible_distribution == "MacOSX"

- name: Install packages with brew
  community.general.homebrew:
    name:
      - git
      - tmux
      - zsh
      - fzf
      - direnv
      - stow
      - docker
    state: present
  when: ansible_distribution == "MacOSX"

- name: Install packages with brew cask
  community.general.homebrew_cask:
    name:
      - iterm2
      - visual-studio-code
      - font-fira-code
    state: present
  when: ansible_distribution == "MacOSX"
